### ISSUE TITLE
关于2.4.1版本汉化的Bug

### ISSUE THREAD

**Issue by Lssg97** [lkyero/GitHubDesktop_zh#7]
2.4.1版本的汉化感觉清晰多了，不过替换汉化文件后点击分支出现了下面的错误：
```
TypeError: r.createElement is not a function
    at S.renderTabBar (file:///app/renderer.js:38921:12)
    at S.render (file:///app/renderer.js:38899:15)
    at v (file:///app/renderer.js:59161:28)
    at beginWork (file:///app/renderer.js:59295:77)
    at a (file:///app/renderer.js:60119:15)
    at e (file:///app/renderer.js:60131:39)
    at A (file:///app/renderer.js:60299:252)
    at n (file:///app/renderer.js:60278:65)
    at M (file:///app/renderer.js:60271:7)
    at b (file:///app/renderer.js:60242:65)

Version: 2.4.1
OS: Windows 10.0.18363
```
我不知道是个例还是通用问题。

**Comment by lkyero** [comment]
Version: 2.4.1汉化时，在38921行汉化时将2个关键字改成了Version: 2.4.0的。
New release修复了Bug
感谢你的反馈~
